// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcaBABeLCUhm_1Xpeg7IO_17ExQjj8KH8',
    appId: '1:236181524844:web:8985a062ee0ad8243ea349',
    messagingSenderId: '236181524844',
    projectId: 'retroflux-cf1ae',
    authDomain: 'retroflux-cf1ae.firebaseapp.com',
    storageBucket: 'retroflux-cf1ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-qUWUgElKigMG-5jnqaePgeRs9gVWLoI',
    appId: '1:236181524844:android:4675e3a62ef3d6433ea349',
    messagingSenderId: '236181524844',
    projectId: 'retroflux-cf1ae',
    storageBucket: 'retroflux-cf1ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_JKiBGAS9_4HrYYHS4gTuOoDCBnullZ8',
    appId: '1:236181524844:ios:3c4cff514641963f3ea349',
    messagingSenderId: '236181524844',
    projectId: 'retroflux-cf1ae',
    storageBucket: 'retroflux-cf1ae.appspot.com',
    iosClientId: '236181524844-ohikheej5uofsbk6bvlr34puebfqfjjc.apps.googleusercontent.com',
    iosBundleId: 'com.retroflux.retroflux',
  );
}
